30 course card
relatable-course-visualization/Relatable pull request #41
Opened 2023-06-06 23:29 UTC by Inioluwa21

Things might not be perfect yet as I would need to integrate the search bar to see how it looks all together.

![image](https://github.com/relatable-course-visualization/Relatable/assets/83588481/aa50fda3-f124-4a4c-8ad4-aec471c3e941)

![image](https://github.com/relatable-course-visualization/Relatable/assets/83588481/955e287c-0350-469f-8dfc-8bd1f6f6d0ec)

2023-06-07 04:27 UTC, marmikpatel19 requested changes

2023-06-07 04:27 UTC, marmikpatel19 commented on client/src/components/courseCard.jsx
> +            Principles and techniques for developing software combined with the
I assume this is an example. If so, we shouldn't commit it

2023-06-07 04:27 UTC, marmikpatel19 commented on client/src/components/coursePage.jsx
> +const courses = [
Similar to above comments. Keep temporary changes like temp data local and not commit them.

2023-06-07 04:28 UTC, marmikpatel19 commented
Search is not in main; let's merge that into this branch to see if things look find with that and footer all together. This may cause (necessary) styling changes.

2023-06-07 04:29 UTC, marmikpatel19 commented
The font in the pictures looks off. Can you confirm that it's the font being used app-wide?

2023-06-07 04:31 UTC, marmikpatel19 commented on client/src/components/courseCard.jsx
> +            {props.body}
Course component seems to missing all the other fields like hyperlink, prerequisites, dependencies, etc. We (I) will do the actual connect the endpoint in another issue, but the course card needs to be ready to display all the necessary content.

2023-06-07 04:31 UTC, marmikpatel19 commented
Colors look quite dull. After adding in all the additional fields, try adding in bits of our primary and/or secondary colors as defined in App.css

2023-06-07 04:33 UTC, marmikpatel19 commented
When done, please attach responsive photos with all new data mocked, as you've done above. Consider cases where certain data is missing, such as prerequisites. In the case of missing data, something else should be displayed to indicate so.

2023-06-10 06:00 UTC, Inioluwa21 commented
![image](https://github.com/relatable-course-visualization/Relatable/assets/83588481/cfd62815-e3be-434e-a41a-45fb8c1c3005)

2023-06-10 06:01 UTC, Inioluwa21 commented
![image](https://github.com/relatable-course-visualization/Relatable/assets/83588481/cc49b062-71b0-465a-b6ee-e3e8ae251489)

2023-06-10 20:19 UTC, marmikpatel19 reviewed
The coursePage.jsx component isn't actually a page--it's embedded inside of the home.jsx page. Could we change its name it be something like courses.jsx and the courseCard.jsx to course.jsx?

2023-06-10 20:20 UTC, marmikpatel19 approved these changes

2023-06-10 20:20 UTC, marmikpatel19 commented
Beyond the comment I left above, everything else looks good--great work!

2023-06-12 01:53 UTC, merged